version: '3'
services:
    server:
        image: node:latest
        volumes:
         - ./server:/app
        networks:
         - backend-network
        working_dir: /app
        command: "node index.js"
        ports:
         - "9888:9888"
    db:
        image: redis:latest
        networks:
         - backend-network
        volumes:
         - redis-volume:/data
        command: ["redis-server", "--appendonly", "yes"]
networks:
    backend-network:
volumes:
    redis-volume:
